name: Sync Main Branch to GitHub

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://ghp.ci/https://github.com/actions/checkout@v4
      - name: Sync to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_OF_GITHUB }}
        run: |
          git remote add github https://github.com/leichongxiang/push-demo.git
          git push github main:main
